export const mockCourses = [
  {
    id: "1",
    title: "Effective Workplace Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/communication.png",
  },
    {
    id: "2",
    title: "Mastering Interpersonal Skills",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Compliance & Policy",
    image: "/images/skills.jpg",
  }, 
  {
    id: "3",
    title: "Strengthening Team Cohesion",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cohesion.jpg",
  },  {
    id: "4",
    title: "Enhancing Team Dialogue",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Digital Skills",
    image: "/images/dialog.jpg",
  }, 
  {
    id: "5",
    title: "Optimizing Group Dynamics",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Business & Strategy",
    image: "/images/dynamics.jpg", 
  },  {
    id: "6",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Onboarding",
    image: "/images/cultivate.jpg",
  },
  {
    id: "7",
    title: "Optimizing Group Dynamics",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/skills.jpg",
  }, 
  {
    id: "8",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg",
  },
  {
    id: "9",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg",
  },
  {
    id: "10",
    title: "Optimizing Group Dynamics",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/dynamics.jpg",
  }, 
  {
    id: "11",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg",
  },
  {
    id: "12",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg",
  },
  {
    id: "13",
    title: "Effective Workplace Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
  },
    {
    id: "14",
    title: "Mastering Interpersonal Skills",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Compliance & Policy",
    image: "/images/skills.jpg",
  }, 
  {
    id: "15",
    title: "Strengthening Team Cohesion",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cohesion.jpg",
  },  {
    id: "16",
    title: "Enhancing Team Dialogue",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Digital Skills",
    image: "/images/dialog.jpg",
  }, 
  {
    id: "17",
    title: "Optimizing Group Dynamics",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Business & Strategy",
    image: "/images/dynamics.jpg",
  },  {
    id: "18",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Onboarding",
    image: "/images/cultivate.jpg",
  },
  {
    id: "19",
    title: "Optimizing Group Dynamics",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/dynamics.jpg",
  }, 
  {
    id: "20",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg", 
  },
  {
    id: "21",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg", 
  },
  {
    id: "22",
    title: "Optimizing Group Dynamics",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/dynamics.jpg",
  }, 
  {
    id: "23",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg", 
  },
  {
    id: "24",
    title: "Cultivating Open Communication",
    description: "Upon completion of this module, participants will: Implement practical communication techniques, ...",
    category: "Soft Skill",
    image: "/images/cultivate.jpg",
  },
];